/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyImport } from './routes/verify'
import { Route as RegisterImport } from './routes/register'
import { Route as RecoveryImport } from './routes/recovery'
import { Route as LoginImport } from './routes/login'
import { Route as SecuredImport } from './routes/_secured'
import { Route as IndexImport } from './routes/index'
import { Route as SecuredProfileImport } from './routes/_secured/profile'

// Create/Update Routes

const VerifyRoute = VerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const RecoveryRoute = RecoveryImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const SecuredRoute = SecuredImport.update({
  id: '/_secured',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SecuredProfileRoute = SecuredProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SecuredRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_secured': {
      id: '/_secured'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SecuredImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyImport
      parentRoute: typeof rootRoute
    }
    '/_secured/profile': {
      id: '/_secured/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SecuredProfileImport
      parentRoute: typeof SecuredImport
    }
  }
}

// Create and export the route tree

interface SecuredRouteChildren {
  SecuredProfileRoute: typeof SecuredProfileRoute
}

const SecuredRouteChildren: SecuredRouteChildren = {
  SecuredProfileRoute: SecuredProfileRoute,
}

const SecuredRouteWithChildren =
  SecuredRoute._addFileChildren(SecuredRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof SecuredRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof SecuredProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof SecuredRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof SecuredProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_secured': typeof SecuredRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/_secured/profile': typeof SecuredProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/recovery'
    | '/register'
    | '/verify'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/recovery' | '/register' | '/verify' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_secured'
    | '/login'
    | '/recovery'
    | '/register'
    | '/verify'
    | '/_secured/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecuredRoute: typeof SecuredRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecuredRoute: SecuredRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_secured",
        "/login",
        "/recovery",
        "/register",
        "/verify"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_secured": {
      "filePath": "_secured.tsx",
      "children": [
        "/_secured/profile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/recovery": {
      "filePath": "recovery.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/verify": {
      "filePath": "verify.tsx"
    },
    "/_secured/profile": {
      "filePath": "_secured/profile.tsx",
      "parent": "/_secured"
    }
  }
}
ROUTE_MANIFEST_END */
