version: v1.2.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:5173
  admin:
    base_url: http://127.0.0.1:4434

selfservice:
  default_browser_return_url: http://127.0.0.1:5173
  flows:
    logout:
      after:
        default_browser_return_url: http://127.0.0.1:5173
    registration:
      ui_url: http://127.0.0.1:5173/register
      enabled: true
    login:
      ui_url: http://127.0.0.1:5173/login
    verification:
      ui_url: http://127.0.0.1:5173/verify
      use: link
      enabled: true
    recovery:
      ui_url: http://127.0.0.1:5173/recovery
      use: link
      enabled: true
    error:
      ui_url: http://127.0.0.1:5173/
    settings:
      ui_url: http://127.0.0.1:5173/settings
  methods:
    password:
      enabled: true
      config:
        min_password_length: 6
        identifier_similarity_check_enabled: false
        haveibeenpwned_enabled: false
  allowed_return_urls:
    - http://127.0.0.1:5173

# selfservice:
#   default_browser_return_url: http://127.0.0.1:4455/
#   allowed_return_urls:
#     - http://127.0.0.1:4455

#   methods:
#     password:
#       enabled: true
#       config:
#         min_password_length: 6
#         identifier_similarity_check_enabled: false
#         haveibeenpwned_enabled: false

#   flows:
#     error:
#       ui_url: http://127.0.0.1:4455/error
#     settings:
#       ui_url: http://127.0.0.1:4455/settings
#       privileged_session_max_age: 15m
#       required_aal: highest_available
#     logout:
#       after:
#         default_browser_return_url: http://127.0.0.1:4455/login
#     login:
#       ui_url: http://127.0.0.1:4455/login
#     registration:
#       ui_url: http://127.0.0.1:4455/registration
#       after:
#         password:
#           hooks:
#             - hook: session

log:
  format: text
  leak_sensitive_values: true
  level: info

secrets:
  cookie:
    - CHANGE_ME_TO_REAL_SECRET
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json # Important: identity schema

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
# oauth2_provider:
#   url: http://hydra:4445 # Important: hydra admin URL
